// Generated by https://quicktype.io

export interface PokemonResponse {
  count:    number;
  next:     string;
  previous: null;
  results:  SmallPokemon[];
}

export interface SmallPokemon {
  id:   number;
  url:  string;
  img:  string;
  name: string;
}
